-- AlterEnum AnalyticsEventType
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'ENERGY_PACK_VIEW';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'ENERGY_PACK_CLICK';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'AUBE_PORTAL_VIEWED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'AUBE_PORTAL_COMPLETED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'AUBE_REFLECTION_REQUESTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'RITUAL_COMPLETED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'ENERGY_BONUS_STREAK';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'LETTER_RUNE_UNLOCKED';
